Repository MRVN-Radiant/MRVN-Radiant, pull requests merged in 2022-11, with the labels that each got.

#3 Add more entities
  games/Titanfall2.game/Titanfall2/entities.ent
Labels: enhancement, entities, editor

#4 Upping CM_GRID bounds to cover all world geo
  tools/remap/source/bspfile_titanfall.cpp
Labels: bug

#7 Updating entity bounds & models
  games/Titanfall2.game/Titanfall2/entities.ent
Labels: enhancement

#20 Add support for mesh flags
  docs/shaders/index.html
  tools/remap/source/bspfile_titanfall.cpp
  tools/remap/source/bspfile_titanfall.h
  tools/remap/source/bspfile_titanfall2.cpp
  tools/remap/source/games.cpp
  tools/remap/source/games.h
  tools/remap/source/map.cpp
Labels: documentation, enhancement, compiler, visibility

#25 Adding compile date and commit sha to github actions artifacts filename
  .github/workflows/build.yml
Labels: enhancement
