Repository MRVN-Radiant/MRVN-Radiant, pull requests merged in 2023-02, with the labels that each got.

#39 General fixes and improvements
  tools/remap/common/scriplib.cpp
  tools/remap/common/vfs.cpp
  tools/remap/source/bsp.cpp
  tools/remap/source/bspfile_apex_legends.cpp
  tools/remap/source/bspfile_apex_legends.h
  tools/remap/source/bspfile_decompile_titanfall.cpp
  tools/remap/source/bspfile_decompile_titanfall.h
  tools/remap/source/bspfile_shared.cpp
  tools/remap/source/bspfile_shared.h
  tools/remap/source/bspfile_titanfall.cpp
  tools/remap/source/bspfile_titanfall.h
  tools/remap/source/bspfile_titanfall2.cpp
  tools/remap/source/bspfile_titanfall2.h
  tools/remap/source/convert_bsp.cpp
  tools/remap/source/games.cpp
  tools/remap/source/games.h
  tools/remap/source/main.cpp
  tools/remap/source/map.cpp
  tools/remap/source/remap.h
  tools/remap/source/shaders.cpp
  tools/remap/source/writebsp.cpp
Labels: enhancement, compiler, editor, visibility

#42 Shader lang improvements
  include/ishaders.h
  plugins/shaders/shaders.cpp
  radiant/texwindow.cpp
  tools/remap/source/bsp.cpp
  tools/remap/source/fog.cpp
  tools/remap/source/games.cpp
  tools/remap/source/games.h
  tools/remap/source/light_trace.cpp
  tools/remap/source/map.cpp
  tools/remap/source/remap.h
  tools/remap/source/shaders.cpp
  tools/remap/source/surface_meta.cpp
Labels: enhancement, compiler, editor

#44 Upping spawnflags limit to 32 bits (#43)
  include/ieclass.h
Labels: bug, enhancement, entities
